[profile.default]
src = "contracts/src"
test = "contracts/test"
out = "contracts/out"
libs = ["contracts/lib"]
solc_version = "0.8.20"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
scroll_sepolia = "${SCROLL_RPC_URL}"
